name: "Build"


on:
  push:
    branches:
      - main

jobs:
  build:
    outputs:
      digest: ${{ steps.build_image.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: docker/build-push-action@v3
        id: build_image
        with:
          push: false
          tags: "docker-hello-world:${{ github.sha }}"
  provenance:
    needs: [build]
    permissions:
      id-token: write
      contents: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/slsa2_provenance.yml@main
    with:
      subjects: "${{ needs.build.outputs.digest }}"